name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags:  dcompanyestall/githubactions_cas2_0:v1
        # Important: Add the load=true option to make the image available for subsequent steps
        load: true
   
    - name: Generate SBOM with Syft
      uses: anchore/sbom-action@v0.15.5
      with:
        image: dcompanyestall/githubactions_cas2_0:v1
        format: "spdx-json"
        output-file: "sbom.spdx.json"

    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v4 # Updated to v4
      with:
        name: sbom-file
        path: sbom.spdx.json
          
