name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: write

    steps:
    - name: Checkout the repository code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags:  dcompanyestall/githubactions_cas2_0:main
        # Important: Add the load=true option to make the image available for subsequent steps
        load: true
   
    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
      with:
        image: "dcompanyestall/githubactions_cas2_0:main"
        artifact-name: sbom-spdx-json
        dependency-snapshot: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v4 # Updated to v4
      with:
        name: sbom-spdx-json
        path: sbom.spdx.json

    # Example: Scan the image for vulnerabilities (optional)
    - name: Trivy vulnerability scan
      run: |
        IMAGE_NAME=dcompanyestall/githubactions_cas2_0:main
        trivy image --format json --output vulnerability-report.json "$IMAGE_NAME"
      
    - name: Upload Vulnerability Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-report.json
        path: vulnerability-report.json 
  
