name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags:  dcompanyestall/githubactions_cas2_0:v1
        
    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
      with:
        image: "dcompanyestall/githubactions_cas2_0:v1"
        artifact-name: githubactions_cas2_0.spdx.json
        dependency-snapshot: true
      
