name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags:  dcompanyestall/githubactions_cas2_0:v1
        # Important: Add the load=true option to make the image available for subsequent steps
        load: true
   
    - name: Generate SBOM with Syft
      run: |
        IMAGE_NAME=dcompanyestall/githubactions_cas2_0:v1  # Or construct dynamically if needed
        docker pull "$IMAGE_NAME" # Pull the image to be able to generate the SBOM.
          syft "docker:$IMAGE_NAME" -o spdx-json > sbom.spdx.json # Use spdx-json for a standard format

    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: sbom.spdx.json
          path: sbom.spdx.json

    # Example: Scan the image for vulnerabilities (optional)
    - name: Trivy vulnerability scan
      run: |
        IMAGE_NAME=dcompanyestall/githubactions_cas2_0:v1
        trivy image --format json --output vulnerability-report.json "$IMAGE_NAME"
      
    - name: Upload Vulnerability Scan Report
      uses: actions/upload-artifact@v3
      with:
        name: vulnerability-report.json
        path: vulnerability-report.json 
  
